### PR TITLE
start translating to traditional Chinese.

### PR DESCRIPTION
**Pull request by yuehhua**

### CODE REVIEW

**Comment by dboyliao** [comment]
我覺得應該要有個 `develop` branch ~
而這些半成品應該進 `develop` ~
最後進 `master` 之前再有最後一次的 proof reading 才合理~

**Comment by yuehhua** [comment]
原本的 repo 也沒有，你要開可以開 develop~

**Comment by dboyliao** [comment]
沒權限喔~XDDD

**Comment by dboyliao** [comment]
OK, looks good to me.

**Pull request merged**
